export const languages = {
	en: 'English',
	ko: '한국어',
} as const;

export type SupportedLanguage = keyof typeof languages;
export const defaultLang: SupportedLanguage = 'en';

export const ui = {
	en: {
		'nav.writing': 'Writing',
		'nav.nakseojang': '낙서장',
		'nav.library': 'Library',
		'lang.switch': '한국어',

		'site.title': 'Duk Lee',
		'site.description': 'Transform your life science business with AI while maintaining GxP compliance and daily IT support. Saram Consulting understands the intersection of biotech and artificial intelligence.',

		'hero.paragraph1': 'I like books, movies and tinkering with computers.',
		'hero.paragraph2': 'My AI agents are working 24/7 building <a href="https://saram.io">tools</a>.',

		'banner.tag': 'Saram Consulting',
		'banner.text': 'GxP compliance and AI integration for life science and biotechnology companies.',
		'banner.linkText': 'Visit saram.io →',

		'contact.label': 'Email',

		'footer.text': 'Website design by Antigravity. Blog articles researched and generated by Heremes Agent with MiniMax-M3.',

		'pagination.newer': '← Newer',
		'pagination.older': 'Older →',

		'post.back': '← Back to Home',
		'post.copyMarkdown': 'Copy Markdown',
		'post.copied': 'Copied!',
		'post.error': 'Error',

		'nakseojang.title': '낙서장',
		'nakseojang.description': 'Thoughts and notes written freely in Korean',

		'library.title': 'Library',
		'library.subtitle': "A visual shelf and log of books I've read, and movies & TV series I've watched.",
		'library.totalLogs': 'Total Logs',
		'library.books': 'Books',
		'library.moviesTv': 'Movies & TV',
		'library.averageRating': 'Average Rating',
		'library.searchPlaceholder': 'Search by title, creator, genre...',
		'library.all': 'All',
		'library.tv': 'TV Series',
		'library.allStatus': 'All Status',
		'library.completed': 'Completed / Read',
		'library.watching': 'Watching / Reading',
		'library.planToWatch': 'Plan to Watch / Read',
		'library.allGenres': 'All Genres',
		'library.latestCompleted': 'Latest Completed',
		'library.ratingHigh': 'Rating: High to Low',
		'library.yearNew': 'Year: New to Old',
		'library.yearOld': 'Year: Old to New',
		'library.alphabetical': 'Title: A to Z',
		'library.perPage': 'per page',
		'library.allItems': 'All items',
		'library.showing': 'Showing all {count} items',
		'library.noMatching': 'No matching logs found.',
		'library.read': 'Read',
		'library.reading': 'Reading',
		'library.planToRead': 'Plan to Read',
		'library.year': 'Year',
		'library.type': 'Type',
		'library.author': 'Author',
		'library.director': 'Director',
		'library.creator': 'Creator',
		'library.status': 'Status',
		'library.rating': 'Rating',
		'library.unrated': 'Unrated',
		'library.notesReview': 'Personal Notes & Review:',
		'library.findOnAmazon': 'Find on Amazon',
		'library.viewOnImdb': 'View on IMDb',
		'library.prev': '← Prev',
		'library.next': 'Next →',
	},
	ko: {
		'nav.writing': '글',
		'nav.nakseojang': '낙서장',
		'nav.library': '서재',
		'lang.switch': 'English',

		'site.title': '이덕희',
		'site.description': '생명과학 및 바이오테크 기업을 위한 GxP 규정 준수와 AI 통합 솔루션. Saram Consulting은 바이오와 인공지능의 접점을 만듭니다.',

		'hero.paragraph1': '책과 영화, 그리고 컴퓨터 다루는 것을 좋아합니다.',
		'hero.paragraph2': '제 AI 에이전트들은 24시간 내내 유용한 <a href="https://saram.io">도구</a>를 만들고 있습니다.',

		'banner.tag': '사람 컨설팅 (Saram Consulting)',
		'banner.text': '생명 과학 및 바이오테크 기업을 위한 GxP 규정 준수 및 AI 통합 솔루션.',
		'banner.linkText': 'saram.io 방문하기 →',

		'contact.label': '이메일',

		'footer.text': '웹사이트 디자인: Antigravity. 블로그 기사는 MiniMax-M3 기반 Hermes Agent가 리서치하고 작성했습니다.',

		'pagination.newer': '← 이전 글',
		'pagination.older': '다음 글 →',

		'post.back': '← 홈으로 돌아가기',
		'post.copyMarkdown': '마크다운 복사',
		'post.copied': '복사됨!',
		'post.error': '오류',

		'nakseojang.title': '낙서장',
		'nakseojang.description': '머릿속에 떠오르는 생각을 자유롭게 적어두는 한글 기록 공간',

		'library.title': '서재',
		'library.subtitle': '읽은 책과 관람한 영화 및 TV 시리즈를 모아둔 개인 서재 및 기록장입니다.',
		'library.totalLogs': '전체 기록',
		'library.books': '도서',
		'library.moviesTv': '영화 & TV',
		'library.averageRating': '평균 평점',
		'library.searchPlaceholder': '제목, 제작자, 장르 검색...',
		'library.all': '전체',
		'library.tv': 'TV 시리즈',
		'library.allStatus': '전체 상태',
		'library.completed': '완료 / 읽음',
		'library.watching': '시청 중 / 읽는 중',
		'library.planToWatch': '볼 예정 / 읽을 예정',
		'library.allGenres': '전체 장르',
		'library.latestCompleted': '최근 완료순',
		'library.ratingHigh': '평점 높은순',
		'library.yearNew': '출시 최신순',
		'library.yearOld': '출시 오래된순',
		'library.alphabetical': '제목 가나다순',
		'library.perPage': '개씩 보기',
		'library.allItems': '전체 보기',
		'library.showing': '총 {count}개 항목 표시 중',
		'library.noMatching': '일치하는 기록을 찾을 수 없습니다.',
		'library.read': '완독',
		'library.reading': '읽는 중',
		'library.planToRead': '읽을 예정',
		'library.year': '출시연도',
		'library.type': '구분',
		'library.author': '저자',
		'library.director': '감독',
		'library.creator': '제작자',
		'library.status': '상태',
		'library.rating': '평점',
		'library.unrated': '평점 없음',
		'library.notesReview': '개인 메모 및 감상:',
		'library.findOnAmazon': '아마존에서 보기',
		'library.viewOnImdb': 'IMDb에서 보기',
		'library.prev': '← 이전',
		'library.next': '다음 →',
	},
} as const;

export type TranslationKey = keyof typeof ui['en'];

export function useTranslations(lang: SupportedLanguage = defaultLang) {
	return function t(key: TranslationKey, params?: Record<string, string | number>): string {
		const langDict = ui[lang] || ui[defaultLang];
		let text: string = (langDict as any)[key] || (ui[defaultLang] as any)[key] || key;
		if (params) {
			Object.entries(params).forEach(([k, v]) => {
				text = text.replace(`{${k}}`, String(v));
			});
		}
		return text;
	};
}

export function getLocalizedPath(pathname: string, targetLocale: SupportedLanguage): string {
	let cleanPath = pathname;
	if (cleanPath.startsWith('/ko/')) {
		cleanPath = cleanPath.slice(3); // keeps leading '/'
	} else if (cleanPath === '/ko') {
		cleanPath = '/';
	}

	if (targetLocale === 'ko') {
		if (cleanPath === '/') return '/ko';
		return `/ko${cleanPath}`;
	}

	return cleanPath || '/';
}

export function formatDate(date: Date, lang: SupportedLanguage = defaultLang): string {
	if (lang === 'ko') {
		return date.toLocaleDateString('ko-KR', {
			year: 'numeric',
			month: 'long',
			day: 'numeric',
			timeZone: 'UTC',
		});
	}
	return date.toLocaleDateString('en-US', {
		year: 'numeric',
		month: 'short',
		day: 'numeric',
		timeZone: 'UTC',
	});
}
